version: '3.3'
services:
  web:
    container_name: php73
    build:
      context: ./
      dockerfile: php-apache.Dockerfile
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html/
    ports:
      - 80:80
  

  db:
    container_name: mariadb10
    image: mariadb:10.4
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass

    ports:
      - 3306:3306